### ISSUE TITLE
Error on successfull scrying

### ISSUE THREAD

**Issue by DoctorVanGogh** [ESOUIMods/ScrySpy#7]
Had an error just now running 1.17
```
user:/AddOns/ScrySpy/ScrySpy.lua:474: table index is nil
stack traceback:
user:/AddOns/ScrySpy/ScrySpy.lua:474: in function 'ScrySpy.update_antiquity_dig_sites'
|caaaaaa<Locals> map_pin_keys = [table:1]{}, polygon_information = [table:2]{}, _ = 42, polygon_location = [table:3]{(null) = 93}, _ = [table:4]{1 = 88}, pin_information = 93, temp_compas_pin_location = [table:5]{y = 1.3212187290192, size = 200, x = 0.22595265507698} </Locals>|r
user:/AddOns/ScrySpy/ScrySpy.lua:482: in function 'OnTrackingUpdate'
|caaaaaa<Locals> eventCode = 131703 </Locals>|r
```

**Comment by Sharlikran** [comment]
I apologize I am not as attentive on my GitHub as I could be mostly because it's more like.... eeehhhh nobody knows what GitHub is. I know there are people that use it and prefer it.

Hopefully this is resolved in the current version, if not please submit a new error with the new lines of code, your SavedVariables file, which zone you were in then this happened, and about where you were standing. I already added a notification but for the most part being in a city means the information I use is not available.

Which is why you have to refresh the data after you leave the city using the slash command.
